environment:
  matrix:
    - TOXENV: py38-coverage

build: off

install:
  - python -m pip install --user git+https://github.com/blueyed/tox@master
  - python -m tox -v --notest --force-dep="pytest @ git+https://github.com/blueyed/pytest@my-master"

test_script:
  - python -m tox -vv --force-dep="pytest @ git+https://github.com/blueyed/pytest@my-master"
