environment:
  matrix:
    - TOXENV: py38

build: off

install:
  - python -m pip install --user git+https://github.com/blueyed/tox@master

test_script:
  - python -m tox --force-dep="pytest @ git+https://github.com/blueyed/pytest@my-master"
